apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secops-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yashbhangale/secops-pipeline
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
