apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-cd.git//manifests/core?ref=stable
  - ingress-argocd.yaml
  - application.yaml
